/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecompensasRouteImport } from './routes/_authenticated/recompensas'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMisPlanesRouteImport } from './routes/_authenticated/mis-planes'
import { Route as AuthenticatedMiGenteRouteImport } from './routes/_authenticated/mi-gente'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedCrearRouteImport } from './routes/_authenticated/crear'
import { Route as AuthenticatedComunidadRouteImport } from './routes/_authenticated/comunidad'
import { Route as AuthenticatedAnfitrionRouteImport } from './routes/_authenticated/anfitrion'
import { Route as AuthenticatedComunidadIndexRouteImport } from './routes/_authenticated/comunidad.index'
import { Route as AuthenticatedUIdRouteImport } from './routes/_authenticated/u.$id'
import { Route as AuthenticatedPlanIdRouteImport } from './routes/_authenticated/plan.$id'
import { Route as AuthenticatedComunidadCategoryRouteImport } from './routes/_authenticated/comunidad.$category'
import { Route as AuthenticatedClubesCompanyRouteImport } from './routes/_authenticated/clubes.$company'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecompensasRoute =
  AuthenticatedRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisPlanesRoute = AuthenticatedMisPlanesRouteImport.update({
  id: '/mis-planes',
  path: '/mis-planes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiGenteRoute = AuthenticatedMiGenteRouteImport.update({
  id: '/mi-gente',
  path: '/mi-gente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrearRoute = AuthenticatedCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadRoute = AuthenticatedComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnfitrionRoute = AuthenticatedAnfitrionRouteImport.update({
  id: '/anfitrion',
  path: '/anfitrion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadIndexRoute =
  AuthenticatedComunidadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComunidadRoute,
  } as any)
const AuthenticatedUIdRoute = AuthenticatedUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanIdRoute = AuthenticatedPlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadCategoryRoute =
  AuthenticatedComunidadCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AuthenticatedComunidadRoute,
  } as any)
const AuthenticatedClubesCompanyRoute =
  AuthenticatedClubesCompanyRouteImport.update({
    id: '/clubes/$company',
    path: '/clubes/$company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/anfitrion': typeof AuthenticatedAnfitrionRoute
  '/comunidad': typeof AuthenticatedComunidadRouteWithChildren
  '/crear': typeof AuthenticatedCrearRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/mi-gente': typeof AuthenticatedMiGenteRoute
  '/mis-planes': typeof AuthenticatedMisPlanesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/clubes/$company': typeof AuthenticatedClubesCompanyRoute
  '/comunidad/$category': typeof AuthenticatedComunidadCategoryRoute
  '/plan/$id': typeof AuthenticatedPlanIdRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/comunidad/': typeof AuthenticatedComunidadIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/anfitrion': typeof AuthenticatedAnfitrionRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/mi-gente': typeof AuthenticatedMiGenteRoute
  '/mis-planes': typeof AuthenticatedMisPlanesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/': typeof AuthenticatedIndexRoute
  '/clubes/$company': typeof AuthenticatedClubesCompanyRoute
  '/comunidad/$category': typeof AuthenticatedComunidadCategoryRoute
  '/plan/$id': typeof AuthenticatedPlanIdRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/comunidad': typeof AuthenticatedComunidadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anfitrion': typeof AuthenticatedAnfitrionRoute
  '/_authenticated/comunidad': typeof AuthenticatedComunidadRouteWithChildren
  '/_authenticated/crear': typeof AuthenticatedCrearRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/mi-gente': typeof AuthenticatedMiGenteRoute
  '/_authenticated/mis-planes': typeof AuthenticatedMisPlanesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/recompensas': typeof AuthenticatedRecompensasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clubes/$company': typeof AuthenticatedClubesCompanyRoute
  '/_authenticated/comunidad/$category': typeof AuthenticatedComunidadCategoryRoute
  '/_authenticated/plan/$id': typeof AuthenticatedPlanIdRoute
  '/_authenticated/u/$id': typeof AuthenticatedUIdRoute
  '/_authenticated/comunidad/': typeof AuthenticatedComunidadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anfitrion'
    | '/comunidad'
    | '/crear'
    | '/empresa'
    | '/mi-gente'
    | '/mis-planes'
    | '/onboarding'
    | '/perfil'
    | '/radar'
    | '/recompensas'
    | '/clubes/$company'
    | '/comunidad/$category'
    | '/plan/$id'
    | '/u/$id'
    | '/comunidad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/anfitrion'
    | '/crear'
    | '/empresa'
    | '/mi-gente'
    | '/mis-planes'
    | '/onboarding'
    | '/perfil'
    | '/radar'
    | '/recompensas'
    | '/'
    | '/clubes/$company'
    | '/comunidad/$category'
    | '/plan/$id'
    | '/u/$id'
    | '/comunidad'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anfitrion'
    | '/_authenticated/comunidad'
    | '/_authenticated/crear'
    | '/_authenticated/empresa'
    | '/_authenticated/mi-gente'
    | '/_authenticated/mis-planes'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/radar'
    | '/_authenticated/recompensas'
    | '/_authenticated/'
    | '/_authenticated/clubes/$company'
    | '/_authenticated/comunidad/$category'
    | '/_authenticated/plan/$id'
    | '/_authenticated/u/$id'
    | '/_authenticated/comunidad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompensas': {
      id: '/_authenticated/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AuthenticatedRecompensasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-planes': {
      id: '/_authenticated/mis-planes'
      path: '/mis-planes'
      fullPath: '/mis-planes'
      preLoaderRoute: typeof AuthenticatedMisPlanesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-gente': {
      id: '/_authenticated/mi-gente'
      path: '/mi-gente'
      fullPath: '/mi-gente'
      preLoaderRoute: typeof AuthenticatedMiGenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crear': {
      id: '/_authenticated/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof AuthenticatedCrearRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidad': {
      id: '/_authenticated/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof AuthenticatedComunidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anfitrion': {
      id: '/_authenticated/anfitrion'
      path: '/anfitrion'
      fullPath: '/anfitrion'
      preLoaderRoute: typeof AuthenticatedAnfitrionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidad/': {
      id: '/_authenticated/comunidad/'
      path: '/'
      fullPath: '/comunidad/'
      preLoaderRoute: typeof AuthenticatedComunidadIndexRouteImport
      parentRoute: typeof AuthenticatedComunidadRoute
    }
    '/_authenticated/u/$id': {
      id: '/_authenticated/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AuthenticatedUIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/$id': {
      id: '/_authenticated/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof AuthenticatedPlanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidad/$category': {
      id: '/_authenticated/comunidad/$category'
      path: '/$category'
      fullPath: '/comunidad/$category'
      preLoaderRoute: typeof AuthenticatedComunidadCategoryRouteImport
      parentRoute: typeof AuthenticatedComunidadRoute
    }
    '/_authenticated/clubes/$company': {
      id: '/_authenticated/clubes/$company'
      path: '/clubes/$company'
      fullPath: '/clubes/$company'
      preLoaderRoute: typeof AuthenticatedClubesCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedComunidadRouteChildren {
  AuthenticatedComunidadCategoryRoute: typeof AuthenticatedComunidadCategoryRoute
  AuthenticatedComunidadIndexRoute: typeof AuthenticatedComunidadIndexRoute
}

const AuthenticatedComunidadRouteChildren: AuthenticatedComunidadRouteChildren =
  {
    AuthenticatedComunidadCategoryRoute: AuthenticatedComunidadCategoryRoute,
    AuthenticatedComunidadIndexRoute: AuthenticatedComunidadIndexRoute,
  }

const AuthenticatedComunidadRouteWithChildren =
  AuthenticatedComunidadRoute._addFileChildren(
    AuthenticatedComunidadRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnfitrionRoute: typeof AuthenticatedAnfitrionRoute
  AuthenticatedComunidadRoute: typeof AuthenticatedComunidadRouteWithChildren
  AuthenticatedCrearRoute: typeof AuthenticatedCrearRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedMiGenteRoute: typeof AuthenticatedMiGenteRoute
  AuthenticatedMisPlanesRoute: typeof AuthenticatedMisPlanesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRecompensasRoute: typeof AuthenticatedRecompensasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClubesCompanyRoute: typeof AuthenticatedClubesCompanyRoute
  AuthenticatedPlanIdRoute: typeof AuthenticatedPlanIdRoute
  AuthenticatedUIdRoute: typeof AuthenticatedUIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnfitrionRoute: AuthenticatedAnfitrionRoute,
  AuthenticatedComunidadRoute: AuthenticatedComunidadRouteWithChildren,
  AuthenticatedCrearRoute: AuthenticatedCrearRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedMiGenteRoute: AuthenticatedMiGenteRoute,
  AuthenticatedMisPlanesRoute: AuthenticatedMisPlanesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRecompensasRoute: AuthenticatedRecompensasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClubesCompanyRoute: AuthenticatedClubesCompanyRoute,
  AuthenticatedPlanIdRoute: AuthenticatedPlanIdRoute,
  AuthenticatedUIdRoute: AuthenticatedUIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
